name: TFKs_HMC
channels:
  - conda-forge
  - defaults
  - omnia
dependencies:
  - autode=1.2.3
  - matplotlib=3.5.1
  - notebook=6.5.4
  - numpy=1.24.3
  - odfpy=1.4.1
  - openpyxl=3.1.2
  - pandas=2.0.1
  - pip=21.2.4
  - plotly=5.14.1
  - python=3.9.13
  - rdkit=2023.03.3
  - scipy=1.10.1
  - tqdm=4.65.0
